export const BITMON_UPDATE_AUTHORITY =
  "Cw4wy1Yg1334gRQ5SxG43Qt5QbM1DM665ur8R6imWGkR";

export enum ATTRIBUTES_INDEX {
  BODY_COLOR,
  MOUTH,
  EYE,
  EYEBROW,
  NOSE,
  HAIR,
  BACK_HAIR,
  BEARD,
  ACCESSORY,
  FACE_ACCESSORY,
  CLOTHES,
  GLASSES,
  BACKGROUND,
}

export const ATTRIBUTES_AMOUNT: { [k: number]: number } = {
  [ATTRIBUTES_INDEX.MOUTH]: 19,
  [ATTRIBUTES_INDEX.EYE]: 15,
  [ATTRIBUTES_INDEX.NOSE]: 6,
  [ATTRIBUTES_INDEX.EYEBROW]: 9,
  [ATTRIBUTES_INDEX.ACCESSORY]: 80,
  [ATTRIBUTES_INDEX.FACE_ACCESSORY]: 22,
  [ATTRIBUTES_INDEX.BACKGROUND]: 15,
  [ATTRIBUTES_INDEX.GLASSES]: 17,
};

export const ATTRIBUTES_PREFIX: { [k: number]: string } = {
  [ATTRIBUTES_INDEX.MOUTH]: "mouth",
  [ATTRIBUTES_INDEX.EYE]: "eye",
  [ATTRIBUTES_INDEX.NOSE]: "nose",
  [ATTRIBUTES_INDEX.EYEBROW]: "eyebrow",
  [ATTRIBUTES_INDEX.ACCESSORY]: "accessory",
  [ATTRIBUTES_INDEX.FACE_ACCESSORY]: "face-accessory",
  [ATTRIBUTES_INDEX.BACKGROUND]: "background",
  [ATTRIBUTES_INDEX.GLASSES]: "glasses",
};
