#!/bin/bash

npx imagemin public/*.png --out-dir=public/
npx imagemin public/icons/*.svg --out-dir=public/icons
npx imagemin public/icons/builder/* --out-dir=public/icons/builder
npx imagemin public/img/* --out-dir=public/img
npx imagemin public/bitmons/* --out-dir=public/bitmons
npx imagemin --plugin.pngquant public/traits/accessories/* --out-dir=public/traits/accessories/
npx imagemin --plugin.pngquant public/traits/backgrounds/* --out-dir=public/traits/backgrounds/
npx imagemin --plugin.pngquant public/traits/eyebrow/* --out-dir=public/traits/eyebrow/
npx imagemin --plugin.pngquant public/traits/mouth/* --out-dir=public/traits/mouth/
npx imagemin --plugin.pngquant public/traits/nose/* --out-dir=public/traits/nose/
npx imagemin --plugin.pngquant public/traits/back-hair/1/* --out-dir=public/traits/back-hair/1/
npx imagemin --plugin.pngquant public/traits/back-hair/2/* --out-dir=public/traits/back-hair/2/
npx imagemin --plugin.pngquant public/traits/back-hair/3/* --out-dir=public/traits/back-hair/3/
npx imagemin --plugin.pngquant public/traits/back-hair/4/* --out-dir=public/traits/back-hair/4/
npx imagemin --plugin.pngquant public/traits/back-hair/5/* --out-dir=public/traits/back-hair/5/
npx imagemin --plugin.pngquant public/traits/back-hair/6/* --out-dir=public/traits/back-hair/6/
npx imagemin --plugin.pngquant public/traits/back-hair/7/* --out-dir=public/traits/back-hair/7/
npx imagemin --plugin.pngquant public/traits/back-hair/8/* --out-dir=public/traits/back-hair/8/
npx imagemin --plugin.pngquant public/traits/back-hair/9/* --out-dir=public/traits/back-hair/9/
npx imagemin --plugin.pngquant public/traits/body/female/* --out-dir=public/traits/body/female
npx imagemin --plugin.pngquant public/traits/body/male/* --out-dir=public/traits/body/male
npx imagemin --plugin.pngquant public/traits/clothes/female/* --out-dir=public/traits/clothes/female
npx imagemin --plugin.pngquant public/traits/clothes/male/* --out-dir=public/traits/clothes/male
npx imagemin --plugin.pngquant public/traits/eyes/1/* --out-dir=public/traits/eyes/1/
npx imagemin --plugin.pngquant public/traits/eyes/2/* --out-dir=public/traits/eyes/2/
npx imagemin --plugin.pngquant public/traits/eyes/3/* --out-dir=public/traits/eyes/3/
npx imagemin --plugin.pngquant public/traits/eyes/4/* --out-dir=public/traits/eyes/4/
npx imagemin --plugin.pngquant public/traits/eyes/5/* --out-dir=public/traits/eyes/5/
npx imagemin --plugin.pngquant public/traits/eyes/6/* --out-dir=public/traits/eyes/6/
npx imagemin --plugin.pngquant public/traits/eyes/7/* --out-dir=public/traits/eyes/7/
npx imagemin --plugin.pngquant public/traits/eyes/8/* --out-dir=public/traits/eyes/8/
npx imagemin --plugin.pngquant public/traits/hair/1/* --out-dir=public/traits/hair/1/
npx imagemin --plugin.pngquant public/traits/hair/2/* --out-dir=public/traits/hair/2/
npx imagemin --plugin.pngquant public/traits/hair/3/* --out-dir=public/traits/hair/3/
npx imagemin --plugin.pngquant public/traits/hair/4/* --out-dir=public/traits/hair/4/
npx imagemin --plugin.pngquant public/traits/hair/5/* --out-dir=public/traits/hair/5/
npx imagemin --plugin.pngquant public/traits/hair/6/* --out-dir=public/traits/hair/6/
npx imagemin --plugin.pngquant public/traits/hair/7/* --out-dir=public/traits/hair/7/
npx imagemin --plugin.pngquant public/traits/hair/8/* --out-dir=public/traits/hair/8/
npx imagemin --plugin.pngquant public/traits/hair/9/* --out-dir=public/traits/hair/9/