export const ACCESSORY: { [k: number]: { image: string; name: string } } = {
  "1": { image: "/traits/accessory/1.png", name: "Cowboy Hat" },
  "2": { image: "/traits/accessory/2.png", name: "Gentleman Hat" },
  "3": { image: "/traits/accessory/3.png", name: "Red Crown" },
  "4": { image: "/traits/accessory/4.png", name: "Blue Crown" },
  "5": { image: "/traits/accessory/5.png", name: "Bitmon Cap" },
  "6": { image: "/traits/accessory/6.png", name: "Irritation Sign" },
  "7": { image: "/traits/accessory/7.png", name: "Cop Hat" },
  "8": { image: "/traits/accessory/8.png", name: "Beanie" },
  "9": { image: "/traits/accessory/9.png", name: "Monkey King" },
  "10": { image: "/traits/accessory/10.png", name: "Bee Antenna" },
  "11": { image: "/traits/accessory/11.png", name: "Horns" },
  "12": { image: "/traits/accessory/12.png", name: "Devil Horns" },
  "13": { image: "/traits/accessory/13.png", name: "Tinfoil Hat" },
  "14": { image: "/traits/accessory/14.png", name: "Geisha" },
  "15": { image: "/traits/accessory/15.png", name: "Black Hat" },
  "16": { image: "/traits/accessory/16.png", name: "Viking Hat" },
  "17": { image: "/traits/accessory/17.png", name: "Deer Ears" },
  "18": { image: "/traits/accessory/18.png", name: "Solana Cap" },
  "19": { image: "/traits/accessory/19.png", name: "Unicorn" },
  "20": { image: "/traits/accessory/20.png", name: "Orange Bow" },
  "21": { image: "/traits/accessory/21.png", name: "Aqua Bow" },
  "22": { image: "/traits/accessory/22.png", name: "Blue Bow" },
  "23": { image: "/traits/accessory/23.png", name: "Purple Bow" },
  "24": { image: "/traits/accessory/24.png", name: "Grey Bow" },
  "25": { image: "/traits/accessory/25.png", name: "Pink Bow" },
  "26": { image: "/traits/accessory/26.png", name: "Green Bow" },
  "27": { image: "/traits/accessory/27.png", name: "Purple Dotted Bow" },
  "28": { image: "/traits/accessory/28.png", name: "Aquia Dotted Bow" },
  "29": { image: "/traits/accessory/29.png", name: "Red Dotted Bow" },
  "30": {
    image: "/traits/accessory/30.png",
    name: "Strawberry Ice Cream Hat",
  },
  "31": {
    image: "/traits/accessory/31.png",
    name: "Chocolate Ice Cream Hat",
  },
  "32": { image: "/traits/accessory/32.png", name: "Mint Ice Cream Hat" },
  "33": { image: "/traits/accessory/33.png", name: "Vanilla Ice Cream Hat" },
  "34": {
    image: "/traits/accessory/34.png",
    name: "Neapolitan Ice Cream Hat",
  },
  "35": { image: "/traits/accessory/35.png", name: "Lemon Ice Cream Hat" },
  "36": {
    image: "/traits/accessory/36.png",
    name: "Cotton Candy Ice Cream Hat",
  },
  "37": { image: "/traits/accessory/37.png", name: "Purple Witch Hat" },
  "38": { image: "/traits/accessory/38.png", name: "Pink Witch Hat" },
  "39": { image: "/traits/accessory/39.png", name: "Blue Witch Hat" },
  "40": { image: "/traits/accessory/40.png", name: "Yellow Witch Hat" },
  "41": { image: "/traits/accessory/41.png", name: "Aqua Witch Hat" },
  "42": {
    image: "/traits/accessory/42.png",
    name: "Purple Dotted Witch Hat",
  },
  "43": { image: "/traits/accessory/43.png", name: "Green Dotted Witch Hat" },
  "44": {
    image: "/traits/accessory/44.png",
    name: "Yellow Dotted Witch Hat",
  },
  "45": { image: "/traits/accessory/45.png", name: "Pink Dotted Witch Hat" },
  "46": { image: "/traits/accessory/46.png", name: "Blue Dotted Witch Hat" },
  "47": { image: "/traits/accessory/47.png", name: "Orange Cap" },
  "48": { image: "/traits/accessory/48.png", name: "Red Cap" },
  "49": { image: "/traits/accessory/49.png", name: "Aqua Cap" },
  "50": { image: "/traits/accessory/50.png", name: "Blue Cap" },
  "51": { image: "/traits/accessory/51.png", name: "Purple Cap" },
  "52": { image: "/traits/accessory/52.png", name: "Grey Cap" },
  "53": { image: "/traits/accessory/53.png", name: "Pink Cap" },
  "54": { image: "/traits/accessory/54.png", name: "Green Cap" },
  "55": { image: "/traits/accessory/55.png", name: "Red Backwards Cap" },
  "56": { image: "/traits/accessory/56.png", name: "Aqua Backwards Cap" },
  "57": { image: "/traits/accessory/57.png", name: "Blue Backwards Cap" },
  "58": { image: "/traits/accessory/58.png", name: "Purple Backwards Cap" },
  "59": { image: "/traits/accessory/59.png", name: "Grey Backwards Cap" },
  "60": { image: "/traits/accessory/60.png", name: "Pink Backwards Cap" },
  "61": { image: "/traits/accessory/61.png", name: "Green Backwards Cap" },
  "62": { image: "/traits/accessory/62.png", name: "Yellow Backwards Cap" },
  "63": { image: "/traits/accessory/63.png", name: "Flowers" },
  "64": { image: "/traits/accessory/64.png", name: "Purple Flower" },
  "65": { image: "/traits/accessory/65.png", name: "Yellow Flower" },
  "66": { image: "/traits/accessory/66.png", name: "Pink Flower" },
  "67": { image: "/traits/accessory/67.png", name: "Aqua Flower" },
  "68": { image: "/traits/accessory/68.png", name: "Purple Flower" },
  "69": { image: "/traits/accessory/69.png", name: "Green Flower" },
  "70": { image: "/traits/accessory/70.png", name: "Red Flower" },
  "71": { image: "/traits/accessory/71.png", name: "Purple Flower" },
  "72": { image: "/traits/accessory/72.png", name: "Grey Flower" },
  "73": { image: "/traits/accessory/73.png", name: "Blue Flower" },
  "74": { image: "/traits/accessory/74.png", name: "Green Beret" },
  "75": { image: "/traits/accessory/75.png", name: "Pink Beret" },
  "76": { image: "/traits/accessory/76.png", name: "White Beret" },
  "77": { image: "/traits/accessory/77.png", name: "Red Beret" },
  "78": { image: "/traits/accessory/78.png", name: "Black Beret" },
  "79": { image: "/traits/accessory/79.png", name: "Red Beret" },
  "80": { image: "/traits/accessory/80.png", name: "Blue Beret" },
};
