export const GLASSES: { [k: number]: { image: string; name: string } } = {
  "1": { image: "/traits/glasses/1.png", name: "Circle Glasses Black" },
  "2": { image: "/traits/glasses/2.png", name: "Pink Glasses Black" },
  "3": { image: "/traits/glasses/3.png", name: "Green Heart Glasses" },
  "4": { image: "/traits/glasses/4.png", name: "Pink Heart Glasses" },
  "5": { image: "/traits/glasses/5.png", name: "Black Heart Glasses" },
  "6": { image: "/traits/glasses/6.png", name: "Black Spiral Glasses" },
  "7": { image: "/traits/glasses/7.png", name: "Pink Spiral Glasses" },
  "8": { image: "/traits/glasses/8.png", name: "Red Spiral Glasses" },
  "9": { image: "/traits/glasses/9.png", name: "Yellow Star Glasses" },
  "10": { image: "/traits/glasses/10.png", name: "Blue Star Glasses" },
  "11": { image: "/traits/glasses/11.png", name: "Green Star Glasses" },
  "12": { image: "/traits/glasses/12.png", name: "Pink Octagon Glasses" },
  "13": { image: "/traits/glasses/13.png", name: "Black Octagon Glasses" },
  "14": { image: "/traits/glasses/14.png", name: "Orange Octagon Glasses" },
  "15": { image: "/traits/glasses/15.png", name: "Black Monocle" },
  "16": { image: "/traits/glasses/16.png", name: "Pink Monocle" },
  "17": { image: "/traits/glasses/17.png", name: "Yellow Monocle" },
};
