export const MOUTH: { [k: number]: { image: string; name: string } } = {
  "1": { image: "/traits/mouth/1.png", name: "Mouth Style 1" },
  "2": { image: "/traits/mouth/2.png", name: "Mouth Style 2" },
  "3": { image: "/traits/mouth/3.png", name: "Mouth Style 3" },
  "4": { image: "/traits/mouth/4.png", name: "Mouth Style 4" },
  "5": { image: "/traits/mouth/5.png", name: "Mouth Style 5" },
  "6": { image: "/traits/mouth/6.png", name: "Mouth Style 6" },
  "7": { image: "/traits/mouth/7.png", name: "Mouth Style 7" },
  "8": { image: "/traits/mouth/8.png", name: "Mouth Style 8" },
  "9": { image: "/traits/mouth/9.png", name: "Mouth Style 9" },
  "10": { image: "/traits/mouth/10.png", name: "Mouth Style 10" },
  "11": { image: "/traits/mouth/11.png", name: "Mouth Style 11" },
  "12": { image: "/traits/mouth/12.png", name: "Mouth Style 12" },
  "13": { image: "/traits/mouth/13.png", name: "Mouth Style 13" },
  "14": { image: "/traits/mouth/14.png", name: "Mouth Style 14" },
  "15": { image: "/traits/mouth/15.png", name: "Mouth Style 15" },
  "16": { image: "/traits/mouth/16.png", name: "Mouth Style 16" },
  "17": { image: "/traits/mouth/17.png", name: "Mouth Style 17" },
  "18": { image: "/traits/mouth/18.png", name: "Mouth Style 18" },
  "19": { image: "/traits/mouth/19.png", name: "Mouth Style 19" },
};
